pool: 'Hosted VS2017'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'pipelines-runner'
    ScriptType: 'Inline'
    Script: | 
      Write-Output "hello-world"
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'