# subscription for demo: e93d3ee6-fac1-412f-92d6-bfb379e81af2 / Contoso IT - SH360 - Prod
pool: 'Hosted VS2017'

variables:
 - name: spnName
   value: 'pipelines-runner'
 - name: blueprintName
   value: 'foundation-with-pci'
 - name: subscriptionId
   value: 'e93d3ee6-fac1-412f-92d6-bfb379e81af2'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

- task: CreateBlueprint@1
  inputs:
    azureSubscription: $(spnName)
    BlueprintName: $(blueprintName)
    BlueprintPath: '.\$(blueprintName)'
    AlternateLocation: false
    PublishBlueprint: true

- task: AssignBlueprint@1
  inputs:
    azureSubscription: $(spnName)
    AssignmentName: 'pla-$(blueprintName)'
    BlueprintName: $(blueprintName)
    ParametersFile: '.\$(blueprintName)\assign.json'
    SubscriptionID: $(subscriptionId)
    Wait: true
    Timeout: 500