pool: 'Hosted VS2017'

variables:
 - name: spnName
   value: 'pipelines-runner'
 - name: blueprintName
   value: 'foundation-with-pci'
 - name: subscriptionId
   value: 'e93d3ee6-fac1-412f-92d6-bfb379e81af2'

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

